name: Build container image

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - README.md
      - docs/**
      - tests/backend/**
      - .pre-commit-config.yaml
      - .github/**
      - "!.github/workflows/image.yaml"
  pull_request:
    paths-ignore:
      - README.md
      - docs/**
      - tests/backend/**
      - .pre-commit-config.yaml
      - .github/**
      - "!.github/workflows/image.yaml"
  workflow_dispatch:

permissions:
  contents: read

env:
  # only publish from this repo, not forks
  PUBLISHING_REPO: jupyterhealth/jupyterhealth-exchange
  REGISTRY: ghcr.io

jobs:

  configure:
    outputs:
      registry: ${{ steps.config.outputs.registry }}
    steps:
      - name: Should we push this image to a public registry?
        id: config
        shell: python
        run: |
          import os
          repo = os.environ["GITHUB_REPOSITORY"]
          event = os.environ["GITHUB_EVENT_NAME"]
          ref = os.environ["GITHUB_REF"]
          if (
              repo == "${{ env.PUBLISHING_REPO }}"
              and event == "push"
              and (
                  ref.startswith("refs/tags/")
                  or ref == "refs/heads/main"
              )
          ):
              registry = os.environ['REGISTRY']
          else:
              registry = "localhost:5000"

          print(f"Publishing image to {registry}")
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              f.write(f"registry={registry}\n")

  build-image:
    name: build ${{ matrix.image_name }}
    needs:
      - configure
    services:
      # So that we can test this in PRs/branches
      local-registry:
        image: registry:2
        ports:
          - 5000:5000

    strategy:
      matrix:
        include:
          - image_name: ${{ github.repository }}
            context: .
          - image_name: ${{ github.repository }}-mcp
            context: mcp_server
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      output: image
      push: true
      meta-tags: |
        type=ref,event=branch
        type=ref,event=tag
        type=sha,prefix=
      meta-images: ${{ needs.configure.outputs.registry }}/${{ matrix.image_name }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
